apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cast-db
  labels:
    app: cast-db
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: cast-db
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: cast-db
        image: "{{ .Values.images.postgres.repository }}:{{ .Values.images.postgres.tag }}"
        imagePullPolicy: {{ .Values.images.postgres.pullPolicy }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: {{ .Values.databases.cast_db.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.databases.cast_db.password }}
        - name: POSTGRES_DB
          value: {{ .Values.databases.cast_db.database }}
        resources:
          requests:
            cpu: {{ .Values.resources.cast_db.requests.cpu }}
            memory: {{ .Values.resources.cast_db.requests.memory }}
          limits:
            cpu: {{ .Values.resources.cast_db.limits.cpu }}
            memory: {{ .Values.resources.cast_db.limits.memory }}
        volumeMounts:
        - name: cast-db-data
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: cast-db-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-cast-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-cast-db
  labels:
    app: cast-db
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: cast-db
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-cast-db-pvc
  labels:
    app: cast-db
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.databases.cast_db.storage }}
